title: Donghwan Shin
logo: /assets/img/DonghwanShin.jpg
description: Research Associate @ SVV group, SnT, University of Luxembourg
show_downloads: false
google_analytics: UA-143928549-1
theme: jekyll-theme-minimal
